### ISSUE TITLE
[BUG] Unable to close Help and Settings pages

### ISSUE THREAD

**Issue by jay-eleven** [baetheus/bee#37]
Hi!

If I open the settings page or the help page, there's no way to close it to get back to playing the game. The only way is to click in the home link and this takes meet out of the game.

Steps to reproduce:

1. Start a daily puzzle 🧩
2. Click help or settings ⚙️❓
3. Try to get back to the puzzle... 🤔😅

Best NYT bee clone I've played...

**Comment by baetheus** [comment]
Does clicking the back button on your browser work?

**Comment by jay-eleven** [comment]
The back button works! I'd swear doing that would take me back to the puzzle list, but I guess I was wrong... 🤷‍♂️

**Comment by baetheus** [comment]
This is still something I've heard more than once, so I think adding a back button to the settings page isn't such a bad idea.
