### ISSUE TITLE
Still some racial slurs

### ISSUE THREAD

**Issue by mogsdad** [baetheus/bee#44]
WRT #11 

“Kike” on June 28, 2022
https://bee.ignoble.dev/games/cehikst_k

**Comment by baetheus** [comment]
Oof! Thanks for the catch!

**Comment by baetheus** [comment]
Fixed in [fa6106f](https://github.com/baetheus/bee/commit/fa6106fda321f9e34d4b531dd7ce01a111211b57)

**Comment by mogsdad** [comment]
More were found by perusing games.20210725.json and comparing it to https://en.wikipedia.org/wiki/List_of_ethnic_slurs. While some may also be inoffensive terms depending on the context, many are only derogatory racial slurs (marked with *). I'm not advocating for the removal of all these, but eliminating the marked ones would be a Good Idea.

- spic *
- bong & bung *
- chichi / chichis
- chug
- dago *
- darkie, darkies *
- dink, dinkies *
- frog, frogs
- golliwog *
- gook *
- guinea
- kebab
- mick *
- nigger, niggers *
- paddies *
- papoose, papooses
- pommy *
- prod
- sheeny
- shine, shiner
- slant, slants
- slope, slopes
- sooty
- spade, spades
- taffy
- teapot
- toad
- whitey *
- yank

**Comment by baetheus** [comment]
Thanks for looking into this more, I've done another pass.
