### ISSUE TITLE
Add new puzzles

### ISSUE THREAD

**Issue by mythiccriminal** [baetheus/bee#46]
The last item in games.20210725.json is for 7/24/2022. Need to generate some new puzzles.

**Comment by baetheus** [comment]
Oh yeah! Looks like another year has come and gone!

**Comment by taylormdavis** [comment]
I searched out your github to say the same haha! I'm a genetics grad student at UC Davis and I play Bee every day! It's my favorite way to let my brain relax, and I look forward to the new puzzle every morning. Some of my lab mates play too, and we like to compete with each other. Thanks for continuing to support it!

**Comment by baetheus** [comment]
Another year of games released!

**Comment by taylormdavis** [comment]
Thanks so much!!!!

On Jul 31, 2022, at 12:45, Brandon Blaylock ***@***.******@***.***>> wrote:



Closed #46<https://github.com/baetheus/bee/issues/46> as completed.

**Comment by taylormdavis** [comment]
Heads up, it seems to be issuing the same letters every day, just in a different order.

On Aug 1, 2022, at 09:00, Taylor M. Davis ***@***.***> wrote:

﻿ Thanks so much!!!!

On Jul 31, 2022, at 12:45, Brandon Blaylock ***@***.******@***.***>> wrote:



Closed #46<https://github.com/baetheus/bee/issues/46> as completed.
