### ISSUE TITLE
Maybe avoid anti-gay slurs

### ISSUE THREAD

**Issue by devilstrumpet** [baetheus/bee#52]
Hi there, I can't be the only person who was puzzled that the dictionary includes "f****t" and "f****ting", words that are banned on social media apps, even for proud gay people (like me) trying to reclaim them and use them positively. Could you update the dictionary to exclude these words, or at least, to make sure that they can't be automatically selected as pangrams or base words? I've noticed that the NYTimes Spelling Bee will sometimes allow edgy words as acceptable word choices but not as pangrams. Thank you!

**Comment by baetheus** [comment]
Absolutely, I apologize for any issues this word has caused. For the most part the dictionary I used is not curated, aside from some initial work I did to remove other slurs that I was either informed of or could think of. I'll update the puzzles and dictionary asap. Thanks for reaching out!

**Comment by baetheus** [comment]
I'll be out of the country until June 15th without a laptop so I won't be able to get to this until I get back. Just wanted to give you a heads up that I haven't forgotten about it.

**Comment by devilstrumpet** [comment]
No worries. Thanks for tending to it when you can.
