### ISSUE TITLE
Please also avoid racial slurs

### ISSUE THREAD

**Issue by TenofClubs** [baetheus/bee#54]
bee.ignoble.dev is my favorite Spelling Bee clone by far. It's clean and well designed, I love the options for viewing the answers one has generated thus far, and I like going back and doing old puzzles too. So I was shocked and disappointed to find that I hadn't cleared a puzzle (low scoring because of the presence of a z) because one of the words I hadn't gotten was a creatively spelled racial slur (clearly designed to slip past filters), specifically the one employed by the late Tupac Shakur in the title of his 1993 album Strictly 4 My _____________. I was going to quit and never look back, but a friend encouraged me to find a way to complain, and that is when I saw the previous ticket from devilstrumpet. It is unbelievable to me that words like "iliac" and "seder" are not words according the list that you use, but a creative spelling of the n-word is. I understand from reading your thread with devilstrumpet that the dictionary you use is not curated and it will be some time before you are able to update your systems, but I hope that you will include this issue in your edits as well, and perhaps consider finding a dictionary that IS curated. 

Thank you for your time and attention.

**Comment by baetheus** [comment]
Hiya, I'm back from my travels and will be taking a look at this today. Thanks for feedback! I would love to use a curated dictionary but don't have a lot of time to devote to this app lately. If you were willing to do a little legwork for me and find one I would definitely be open to doing the work to implement it.

Again, thanks for responding and sorry that some of the words caused you distress.
