### ISSUE TITLE
Prevent zoom when double tapping on mobile

### ISSUE THREAD

**Issue by kodyyuen** [baetheus/bee#60]
Hi, I often accidentally zoom when double-tapping letters/backspace when I'm playing on my phone. I saw that CSS has a property to prevent this (https://stackoverflow.com/questions/10614481/disable-double-tap-zoom-option-in-browser-on-touch-devices). I was hoping that this can be implemented to prevent this issue. Thanks!

**Comment by baetheus** [comment]
Good find! This is deployed from de1bac9 and looks like it works on my iphone. You'll have to refresh the app (just browser refresh) to get the change. Take care, and thanks for opening an issue and doing some research.
