### ISSUE TITLE
I love playing the Ignoble Bee - how come no new puzzles? I also write clues for the NYTimes Spelling Bee, but the hours are killing me (3am is the new puzzle drop each day)! Let me know if you'd like me to write clues for your puzzle!

### ISSUE THREAD

**Issue by KittRichards** [baetheus/bee#61]

**Comment by KittRichards** [comment]
PS I also write clues for the NYTimes Spelling Bee, but the hours are killing me (3am is the new puzzle drop each day)! Let me know if you'd like me to write clues for your puzzle!

**Comment by baetheus** [comment]
Hiya Kitt! I've been rewriting the bee for a couple of months now in my spare time. I'd love to hear your thoughts on how I could integrate better hints. One of my thoughts is to expand bee to include a few other languages, types of puzzles, and accounts so you can play across devices.

**Comment by KittRichards** [comment]
Hi, Brandon!

I'm no coder - I'm a creative - so I don't have any suggestions on how to
integrate hints electronically, but I'm one of the top hint-writers for the
Times (they use my hints in their Spelling Bee Buddy tool, and published an
article about us in April):

https://www.nytimes.com/2024/04/01/crosswords/spelling-bee-hints.html

The downside is I have to write them at 3am(!) which (obviously) disrupts
my sleep...so if you would like someone to write fun, entertaining clues
for your puzzle (and could let me do it at a reasonable hour!), I'd be
happy to help on that creative front.

Kitt
